services:
  postgres:
    image: postgres:alpine
    container_name: throne-squad-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"